#pragma once

const int I_NO_ERROR = 0;

const int I_ERROR_MATRIX_NOT_CREATED_INCORRECT_SIZE = 1;

const int I_ERROR_METHOD_FAILED_MATRIX_IS_NULL = 2;

const int I_ERROR_IDENTITY_MATRIX_NOT_FILLED_MATRIX_NOT_SQUARE = 3;

const int I_ERROR_ELEMENT_NOT_FOUND_INCORRECT_INDEX = 4;

const int I_ERROR_METHOD_FAILED_INCORRECT_MATRIX_SIZES = 5;

const int I_ERROR_MATRIX_NOT_CREATED_CANNOT_OPEN_FILE = 6;

const int I_ERROR_MATRIX_CREATED_INVALID_ELEMENTS_REPLACED = 7;
